### ISSUE TITLE
Nuget Package(s)

### ISSUE THREAD

**Issue by Thieum** [brianlagunas/InfragisticsThemesForMicrosoftControls#1]
Would be nice to have a nuget package, or individual nuget packages for each themes.
They could at least import the xaml files in the project, and document the needed edits to views / app.xaml.

And reference the dependency on WPFToolkit ( https://www.nuget.org/packages/WPFToolkit/ )

**Comment by brianlagunas** [comment]
That's a great idea.  Thanks for submitting it.  I'll see what I can do.

**Comment by brianlagunas** [comment]
Here are the WPF versions:
https://www.nuget.org/packages/Infragistics.Themes.IG.Wpf/
https://www.nuget.org/packages/Infragistics.Themes.MetroDark.Wpf/
https://www.nuget.org/packages/Infragistics.Themes.MetroLight.Wpf/
https://www.nuget.org/packages/Infragistics.Themes.Office2010Blue.Wpf/
https://www.nuget.org/packages/Infragistics.Themes.Office2013.Wpf/

**Comment by brianlagunas** [comment]
Oh, and I didn't add a dependency on the WPFToolkit NuGet package because it wasn't and official Microsoft package.  So I just included the dependent assemblies in the theme packages.

**Comment by brianlagunas** [comment]
And here are the Silverlight versions:
https://www.nuget.org/packages/Infragistics.Themes.IG.SL/
https://www.nuget.org/packages/Infragistics.Themes.MetroDark.SL/
https://www.nuget.org/packages/Infragistics.Themes.MetroLight.SL/
https://www.nuget.org/packages/Infragistics.Themes.Office2010Blue.SL/

**Comment by Thieum** [comment]
Thanks a lot !
I understand for the reference to WPFToolkit. For future reference, people should go vote for official package here: http://wpf.codeplex.com/workitem/15812 

it's a bit meta to the present discussion, but it would be nice if Infragistics would adopt the wpftoolkit project like DevExpress did for the Ajax Control Toolkit - http://blogs.msdn.com/b/webdev/archive/2014/09/30/the-ajax-control-toolkit-are-now-maintained-by-devexpress.aspx
